
version: '2'

services:
  db:
    image: postgres:10
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    restart: always
    environment:
      - BACKUP_DATABASE=true
      - BACKUP_DATABASE_TYPE=postgres
      - BACKUP_DATABASE_USER=postgres
      - BACKUP_DATABASE_PASSWORD=password
      - BACKUP_DATABASE_NAMES=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  cookbookserv-nginx:
    image: nginx
    container_name: cookbookserv-nginx
    volumes:
      - "./volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./volumes/static/:/static"
      - "./volumes/well-known/:/well-known"
    environment:
      - VIRTUAL_HOST=wcs.example.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=wcs.example.org
      - LETSENCRYPT_EMAIL=mail@example.org
    depends_on:
      - db
    networks:
      - default
      - external

  wcs-web:
    build: cookbook_webservice/
    command: uwsgi --ini mysite_uwsgi.ini
    volumes:
      - ./cookbook_webservice:/code
      - ./volumes/static:/static
      - ./.git/HEAD:/code/.git/HEAD:ro
      - ./.git/refs:/code/.git/refs:ro
    expose:
      - "8099"
    links:
      - "db:db"
    depends_on:
      - db
    networks:
      - default

networks:
  external:
    external:
      name: network_main_net
