
version: '2'

services:
  db:
    image: postgres:10
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      - BACKUP_DATABASE=true
      - BACKUP_DATABASE_TYPE=postgres
      - BACKUP_DATABASE_USER=postgres
      - BACKUP_DATABASE_PASSWORD=password
      - BACKUP_DATABASE_NAMES=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    labels:
     - "traefik.enable=false"



  nginx:
    image: nginx
    volumes:
      - "./volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./volumes/static/:/static"
      - "./volumes/well-known/:/well-known"
    depends_on:
      - db
      - web
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:wcs.henkela.de"
      - "traefik.basic.frontent.port=8000"
      - "traefik.passHostHeader=true"
    networks:
      - default
      - proxy
  
  angular:
    build: webserviceFrontend/
    volumes:
      - './webserviceFrontend:/app'
      - './volumes/node_modules:/app/node_modules'
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:wcsb.henkela.de"
      - "traefik.basic.frontent.port=80"
    networks:
      - default
      - proxy

  web:
    build: cookbook_webservice/
    command: daphne cookbookserv.asgi:application
    volumes:
      - ./cookbook_webservice:/code
      - ./volumes/static:/static
      - ./.git/HEAD:/code/.git/HEAD:ro
      - ./.git/refs:/code/.git/refs:ro
    labels:
      - "traefik.enable=false"
    links:
      - "db:db"
    depends_on:
      - db
    networks:
      - default

networks:
  proxy:
    external: true
