# Generated by Django 2.2.1 on 2019-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0002_unit_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='short',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
