# Generated by Django 2.2.1 on 2019-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_auto_20190504_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='webportal.Tag'),
        ),
    ]
