# Generated by Django 2.2.1 on 2019-05-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0005_recipe_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='profile_image',
            new_name='image',
        ),
    ]
