# Generated by Django 2.2.1 on 2019-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0009_auto_20190505_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='webportal.Ingredient'),
        ),
    ]
